
from lightshow_classes import Song

def carol_of_the_bells():

    carol = Song(140)

    carol.name = "Carol Of The Bells"

    carol.notes.append([carol.d, carol.quarter])
    carol.notes.append([carol.e, carol.quarter])
    carol.notes.append([carol.f, carol.quarter])

    carol.notes.append([carol.b, carol.quarter])
    carol.notes.append([carol.a, carol.eighth])
    carol.notes.append([carol.b, carol.eighth])
    carol.notes.append([carol.g, carol.quarter])
    carol.notes.append([carol.b, carol.quarter])
    carol.notes.append([carol.a, carol.eighth])
    carol.notes.append([carol.b, carol.eighth])
    carol.notes.append([carol.g, carol.quarter])
    carol.notes.append([carol.b, carol.quarter])
    carol.notes.append([carol.a, carol.eighth])
    carol.notes.append([carol.b, carol.eighth])
    carol.notes.append([carol.g, carol.quarter])
    carol.notes.append([carol.b, carol.quarter])
    carol.notes.append([carol.a, carol.eighth])
    carol.notes.append([carol.b, carol.eighth])
    carol.notes.append([carol.g, carol.quarter])

    carol.notes.append([carol.d, carol.quarter])
    carol.notes.append([carol.c, carol.eighth])
    carol.notes.append([carol.d, carol.eighth])
    carol.notes.append([carol.b, carol.quarter])
    carol.notes.append([carol.d, carol.quarter])
    carol.notes.append([carol.c, carol.eighth])
    carol.notes.append([carol.d, carol.eighth])
    carol.notes.append([carol.b, carol.quarter])
    carol.notes.append([carol.d, carol.quarter])
    carol.notes.append([carol.c, carol.eighth])
    carol.notes.append([carol.d, carol.eighth])
    carol.notes.append([carol.b, carol.quarter])
    carol.notes.append([carol.d, carol.quarter])
    carol.notes.append([carol.c, carol.eighth])
    carol.notes.append([carol.d, carol.eighth])
    carol.notes.append([carol.b, carol.quarter])

    carol.notes.append([carol.g, carol.quarter])
    carol.notes.append([carol.g, carol.eighth])
    carol.notes.append([carol.g, carol.eighth])
    carol.notes.append([carol.f, carol.eighth])
    carol.notes.append([carol.e, carol.eighth])
    carol.notes.append([carol.d, carol.quarter])
    carol.notes.append([carol.d, carol.eighth])
    carol.notes.append([carol.d, carol.eighth])
    carol.notes.append([carol.c, carol.eighth])
    carol.notes.append([carol.b, carol.eighth])
    carol.notes.append([carol.c, carol.quarter])
    carol.notes.append([carol.c, carol.eighth])
    carol.notes.append([carol.c, carol.eighth])
    carol.notes.append([carol.d, carol.eighth])
    carol.notes.append([carol.c, carol.eighth])
    carol.notes.append([carol.b, carol.quarter])
    carol.notes.append([carol.a, carol.eighth])
    carol.notes.append([carol.b, carol.eighth])
    carol.notes.append([carol.g, carol.quarter])

    carol.notes.append([carol.d, carol.eighth])
    carol.notes.append([carol.e, carol.eighth])
    carol.notes.append([carol.f, carol.eighth])
    carol.notes.append([carol.g, carol.eighth])
    carol.notes.append([carol.a, carol.eighth])
    carol.notes.append([carol.b, carol.eighth])
    carol.notes.append([carol.c, carol.eighth])
    carol.notes.append([carol.d, carol.eighth])
    carol.notes.append([carol.c, carol.quarter])
    carol.notes.append([carol.b, carol.quarter])
    carol.notes.append([carol.d, carol.eighth])
    carol.notes.append([carol.e, carol.eighth])
    carol.notes.append([carol.f, carol.eighth])
    carol.notes.append([carol.g, carol.eighth])
    carol.notes.append([carol.a, carol.eighth])
    carol.notes.append([carol.b, carol.eighth])
    carol.notes.append([carol.c, carol.eighth])
    carol.notes.append([carol.d, carol.eighth])
    carol.notes.append([carol.c, carol.quarter])
    carol.notes.append([carol.b, carol.quarter])

    carol.notes.append([carol.b, carol.quarter])
    carol.notes.append([carol.a, carol.eighth])
    carol.notes.append([carol.b, carol.eighth])
    carol.notes.append([carol.g, carol.quarter])
    carol.notes.append([carol.b, carol.quarter])
    carol.notes.append([carol.a, carol.eighth])
    carol.notes.append([carol.b, carol.eighth])
    carol.notes.append([carol.g, carol.quarter])
    carol.notes.append([carol.d, carol.quarter])
    carol.notes.append([carol.c, carol.eighth])
    carol.notes.append([carol.d, carol.eighth])
    carol.notes.append([carol.b, carol.quarter])
    carol.notes.append([carol.d, carol.quarter])
    carol.notes.append([carol.c, carol.eighth])
    carol.notes.append([carol.d, carol.eighth])
    carol.notes.append([carol.b, carol.quarter])

    carol.notes.append([carol.g, carol.half*1.5])

    carol.size = len(carol.notes)
 
    return carol


