
from lightshow_classes import Song

def deck_the_halls():

    deck = Song(140)

    deck.name = "Deck The Halls"

    deck.notes.append([deck.g, deck.quarter+deck.eighth])
    deck.notes.append([deck.f, deck.eighth])
    deck.notes.append([deck.e, deck.quarter])
    deck.notes.append([deck.d, deck.quarter])
    deck.notes.append([deck.c, deck.quarter])
    deck.notes.append([deck.d, deck.quarter])
    deck.notes.append([deck.e, deck.quarter])
    deck.notes.append([deck.c, deck.quarter])
    deck.notes.append([deck.d, deck.eighth])
    deck.notes.append([deck.e, deck.eighth])
    deck.notes.append([deck.f, deck.eighth])
    deck.notes.append([deck.d, deck.eighth])
    deck.notes.append([deck.e, deck.quarter+deck.eighth])
    deck.notes.append([deck.d, deck.eighth])
    deck.notes.append([deck.c, deck.quarter])
    deck.notes.append([deck.b, deck.quarter])
    deck.notes.append([deck.c, deck.half])

    deck.notes.append([deck.g, deck.quarter+deck.eighth])
    deck.notes.append([deck.f, deck.eighth])
    deck.notes.append([deck.e, deck.quarter])
    deck.notes.append([deck.d, deck.quarter])
    deck.notes.append([deck.c, deck.quarter])
    deck.notes.append([deck.d, deck.quarter])
    deck.notes.append([deck.e, deck.quarter])
    deck.notes.append([deck.c, deck.quarter])
    deck.notes.append([deck.d, deck.eighth])
    deck.notes.append([deck.e, deck.eighth])
    deck.notes.append([deck.f, deck.eighth])
    deck.notes.append([deck.d, deck.eighth])
    deck.notes.append([deck.e, deck.quarter+deck.eighth])
    deck.notes.append([deck.d, deck.eighth])
    deck.notes.append([deck.c, deck.quarter])
    deck.notes.append([deck.b, deck.quarter])
    deck.notes.append([deck.c, deck.half])

    deck.notes.append([deck.d, deck.quarter+deck.eighth])
    deck.notes.append([deck.e, deck.eighth])
    deck.notes.append([deck.f, deck.quarter])
    deck.notes.append([deck.d, deck.quarter])
    deck.notes.append([deck.e, deck.quarter+deck.eighth])
    deck.notes.append([deck.f, deck.eighth])
    deck.notes.append([deck.g, deck.quarter])
    deck.notes.append([deck.d, deck.quarter])
    deck.notes.append([deck.e, deck.eighth])
    deck.notes.append([deck.f, deck.eighth])
    deck.notes.append([deck.g, deck.quarter])
    deck.notes.append([deck.a, deck.eighth])
    deck.notes.append([deck.b, deck.eighth])
    deck.notes.append([deck.c, deck.quarter])
    deck.notes.append([deck.b, deck.quarter])
    deck.notes.append([deck.a, deck.quarter])
    deck.notes.append([deck.g, deck.half])

    deck.notes.append([deck.g, deck.quarter+deck.eighth])
    deck.notes.append([deck.f, deck.eighth])
    deck.notes.append([deck.e, deck.quarter])
    deck.notes.append([deck.d, deck.quarter])
    deck.notes.append([deck.c, deck.quarter])
    deck.notes.append([deck.d, deck.quarter])
    deck.notes.append([deck.e, deck.quarter])
    deck.notes.append([deck.c, deck.quarter])
    deck.notes.append([deck.a, deck.eighth])
    deck.notes.append([deck.a, deck.eighth])
    deck.notes.append([deck.a, deck.eighth])
    deck.notes.append([deck.a, deck.eighth])
    deck.notes.append([deck.g, deck.quarter+deck.eighth])
    deck.notes.append([deck.f, deck.eighth])
    deck.notes.append([deck.e, deck.quarter])
    deck.notes.append([deck.d, deck.quarter])
    deck.notes.append([deck.c, deck.half])

    deck.size = len(deck.notes)
 
    return deck 


