
from lightshow_classes import Song

def hark_the_herald_angels_sing():

    hark = Song(140)


    hark.notes.append([hark.g, hark.quarter])
    hark.notes.append([hark.c, hark.quarter])
    hark.notes.append([hark.c, hark.quarter*1.5])
    hark.notes.append([hark.b, hark.eigth])
    hark.notes.append([hark.c, hark.quarter])
    hark.notes.append([hark.e, hark.quarter])
    hark.notes.append([hark.e, hark.quarter])
    hark.notes.append([hark.d, hark.quarter])
    hark.notes.append([hark.g, hark.quarter])
    hark.notes.append([hark.g, hark.quarter])
    hark.notes.append([hark.g, hark.quarter*1.5])
    hark.notes.append([hark.f, hark.eigth])
    hark.notes.append([hark.e, hark.quarter])
    hark.notes.append([hark.d, hark.quarter])
    hark.notes.append([hark.e, hark.half])
    hark.notes.append([hark.g, hark.quarter])
    hark.notes.append([hark.c, hark.quarter])
    hark.notes.append([hark.c, hark.quarter*1.5])
    hark.notes.append([hark.b, hark.eigth])

    hark.notes.append([hark.c, hark.quarter])
    hark.notes.append([hark.e, hark.quarter])
    hark.notes.append([hark.e, hark.quarter])
    hark.notes.append([hark.d, hark.quarter])
    hark.notes.append([hark.g, hark.quarter])
    hark.notes.append([hark.d, hark.quarter])
    hark.notes.append([hark.d, hark.quarter*1.5])
    hark.notes.append([hark.c, hark.eigth])
    hark.notes.append([hark.b, hark.quarter])
    hark.notes.append([hark.a, hark.quarter])
    hark.notes.append([hark.g, hark.half])
    hark.notes.append([hark.g, hark.quarter])
    hark.notes.append([hark.g, hark.quarter])
    hark.notes.append([hark.g, hark.quarter])
    hark.notes.append([hark.c, hark.quarter])
    hark.notes.append([hark.f, hark.quarter])
    hark.notes.append([hark.e, hark.quarter])
    hark.notes.append([hark.e, hark.quarter])
    hark.notes.append([hark.d, hark.quarter])

    hark.notes.append([hark.g, hark.quarter])
    hark.notes.append([hark.g, hark.quarter])
    hark.notes.append([hark.g, hark.quarter])
    hark.notes.append([hark.c, hark.quarter])
    hark.notes.append([hark.f, hark.quarter])
    hark.notes.append([hark.e, hark.quarter])
    hark.notes.append([hark.e, hark.quarter])
    hark.notes.append([hark.d, hark.quarter])
    hark.notes.append([hark.a, hark.quarter*1.5])
    hark.notes.append([hark.a, hark.eigth])
    hark.notes.append([hark.a, hark.quarter])
    hark.notes.append([hark.g, hark.quarter])
    hark.notes.append([hark.f, hark.quarter])
    hark.notes.append([hark.e, hark.quarter])
    hark.notes.append([hark.f, hark.half])
    hark.notes.append([hark.d, hark.quarter])
    hark.notes.append([hark.e, hark.eigth])
    hark.notes.append([hark.f, hark.eigth])
    hark.notes.append([hark.g, hark.quarter*1.5])
    hark.notes.append([hark.c, hark.eigth])

    hark.notes.append([hark.c, hark.quarter])
    hark.notes.append([hark.d, hark.quarter])
    hark.notes.append([hark.e, hark.half])
    hark.notes.append([hark.a, hark.quarter*1.5])
    hark.notes.append([hark.a, hark.eigth])
    hark.notes.append([hark.a, hark.quarter])
    hark.notes.append([hark.g, hark.quarter])
    hark.notes.append([hark.f, hark.quarter])
    hark.notes.append([hark.e, hark.quarter])
    hark.notes.append([hark.f, hark.half])
    hark.notes.append([hark.d, hark.quarter])
    hark.notes.append([hark.e, hark.eigth])
    hark.notes.append([hark.f, hark.eigth])
    hark.notes.append([hark.g, hark.quarter*1.5])
    hark.notes.append([hark.c, hark.eigth])
    hark.notes.append([hark.c, hark.quarter])
    hark.notes.append([hark.d, hark.quarter])
    hark.notes.append([hark.c, hark.half])

    hark.size = len(hark.notes)
 
    return hark 


