
from lightshow_classes import Song

def jingle_bells():

    jingle = Song(160)

    jingle.name = "Jingle Bells"

    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.half])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.half])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.quarter+jingle.eighth])
    jingle.notes.append([jingle.g, jingle.eighth])
    jingle.notes.append([jingle.a, jingle.whole])

    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter+jingle.eighth])
    jingle.notes.append([jingle.b, jingle.eighth])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.eighth])
    jingle.notes.append([jingle.a, jingle.eighth])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.half])
    jingle.notes.append([jingle.c, jingle.half])

    jingle.notes.append([jingle.c, jingle.quarter])  # Dash
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.quarter])
    jingle.notes.append([jingle.c, jingle.whole])
    jingle.notes.append([jingle.c, jingle.eighth])
    jingle.notes.append([jingle.c, jingle.eighth])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.quarter])
    jingle.notes.append([jingle.d, jingle.whole])
    
    jingle.notes.append([jingle.d, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.whole])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.whole])

    jingle.notes.append([jingle.c, jingle.quarter])  # Bells
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.quarter])
    jingle.notes.append([jingle.c, jingle.whole])
    jingle.notes.append([jingle.c, jingle.quarter])  
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.quarter])
    jingle.notes.append([jingle.d, jingle.whole])
    jingle.notes.append([jingle.d, jingle.quarter])  
    jingle.notes.append([jingle.d, jingle.quarter])  
    jingle.notes.append([jingle.b, jingle.quarter])  
    jingle.notes.append([jingle.a, jingle.quarter])  
    jingle.notes.append([jingle.g, jingle.quarter])  
    jingle.notes.append([jingle.c, jingle.quarter])  
    jingle.notes.append([jingle.c, jingle.quarter])  
    jingle.notes.append([jingle.c, jingle.quarter])  
    jingle.notes.append([jingle.c, jingle.quarter])  
    jingle.notes.append([jingle.d, jingle.quarter])  
    jingle.notes.append([jingle.c, jingle.quarter])  
    jingle.notes.append([jingle.b, jingle.quarter])  
    jingle.notes.append([jingle.g, jingle.quarter])  
    jingle.notes.append([jingle.f, jingle.half])  
    jingle.notes.append([jingle.c, jingle.half])  

    jingle.notes.append([jingle.a, jingle.quarter])  # Jingle
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.half])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.half])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.quarter+jingle.eighth])
    jingle.notes.append([jingle.g, jingle.eighth])
    jingle.notes.append([jingle.a, jingle.whole])

    jingle.notes.append([jingle.b, jingle.quarter])  # Oh
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter+jingle.eighth])
    jingle.notes.append([jingle.b, jingle.eighth])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.eighth])
    jingle.notes.append([jingle.a, jingle.eighth])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.half])
    jingle.notes.append([jingle.c, jingle.half])

    jingle.notes.append([jingle.a, jingle.quarter])  # Jingle
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.half])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.half])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.quarter+jingle.eighth])
    jingle.notes.append([jingle.g, jingle.eighth])
    jingle.notes.append([jingle.a, jingle.whole])
 
    jingle.notes.append([jingle.b, jingle.quarter])  # Oh
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter+jingle.eighth])
    jingle.notes.append([jingle.b, jingle.eighth])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.eighth])
    jingle.notes.append([jingle.a, jingle.eighth])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.whole])


    jingle.size = len(jingle.notes)
 
    return jingle 


