
from lightshow_classes import Song

def jingle_bells():

    jingle = Song(160)


    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.half])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.half])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.quarter+jingle.eigth])
    jingle.notes.append([jingle.g, jingle.eigth])
    jingle.notes.append([jingle.a, jingle.whole])

    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter+jingle.eigth])
    jingle.notes.append([jingle.b, jingle.eigth])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.eigth])
    jingle.notes.append([jingle.a, jingle.eigth])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.half])
    jingle.notes.append([jingle.c, jingle.half])

    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.half])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.half])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.quarter+jingle.eigth])
    jingle.notes.append([jingle.g, jingle.eigth])
    jingle.notes.append([jingle.a, jingle.whole])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter])

    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.eigth])
    jingle.notes.append([jingle.a, jingle.eigth])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.whole])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.quarter])
    jingle.notes.append([jingle.c, jingle.half+jingle.quarter])
    jingle.notes.append([jingle.c, jingle.eigth])
    jingle.notes.append([jingle.c, jingle.eigth])
 
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.quarter])
    jingle.notes.append([jingle.d, jingle.whole])
    jingle.notes.append([jingle.d, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.e, jingle.whole])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.b, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])

    jingle.notes.append([jingle.a, jingle.whole])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.quarter])
    jingle.notes.append([jingle.c, jingle.whole])
    jingle.notes.append([jingle.c, jingle.quarter])
    jingle.notes.append([jingle.a, jingle.quarter])
    jingle.notes.append([jingle.g, jingle.quarter])
    jingle.notes.append([jingle.f, jingle.quarter])
    jingle.notes.append([jingle.d, jingle.whole])

    jingle.size = len(jingle.notes)
 
    return jingle 


