
from lightshow_classes import Song

def the_first_noel():

    noel = Song(100)


    noel.notes.append([noel.g, noel.eigth])
    noel.notes.append([noel.f, noel.eigth])
    noel.notes.append([noel.e, noel.quarter*1.5])
    noel.notes.append([noel.f, noel.eigth])
    noel.notes.append([noel.g, noel.eigth])
    noel.notes.append([noel.a, noel.eigth])
    noel.notes.append([noel.d, noel.half])
    noel.notes.append([noel.e, noel.eigth])
    noel.notes.append([noel.f, noel.eigth])
    noel.notes.append([noel.g, noel.quarter])
    noel.notes.append([noel.f, noel.quarter])
    noel.notes.append([noel.e, noel.quarter])
    noel.notes.append([noel.d, noel.half])
    noel.notes.append([noel.e, noel.eigth])
    noel.notes.append([noel.f, noel.eigth])

    noel.notes.append([noel.g, noel.quarter])
    noel.notes.append([noel.f, noel.quarter])
    noel.notes.append([noel.e, noel.quarter])
    noel.notes.append([noel.d, noel.quarter])
    noel.notes.append([noel.e, noel.quarter])
    noel.notes.append([noel.f, noel.quarter])
    noel.notes.append([noel.g, noel.quarter])
    noel.notes.append([noel.d, noel.quarter])
    noel.notes.append([noel.a, noel.quarter])
    noel.notes.append([noel.g, noel.half])
    noel.notes.append([noel.g, noel.eigth])
    noel.notes.append([noel.f, noel.eigth])
    noel.notes.append([noel.e, noel.quarter*1.5])
    noel.notes.append([noel.f, noel.eigth])
    noel.notes.append([noel.g, noel.eigth])
    noel.notes.append([noel.a, noel.eigth])

    noel.notes.append([noel.d, noel.half])
    noel.notes.append([noel.e, noel.eigth])
    noel.notes.append([noel.f, noel.eigth])
    noel.notes.append([noel.g, noel.quarter])
    noel.notes.append([noel.f, noel.quarter])
    noel.notes.append([noel.e, noel.quarter])
    noel.notes.append([noel.d, noel.half])
    noel.notes.append([noel.e, noel.eigth])
    noel.notes.append([noel.f, noel.eigth])
    noel.notes.append([noel.g, noel.quarter])
    noel.notes.append([noel.f, noel.quarter])
    noel.notes.append([noel.e, noel.quarter])
    noel.notes.append([noel.d, noel.quarter])
    noel.notes.append([noel.e, noel.quarter])
    noel.notes.append([noel.f, noel.quarter])

    noel.notes.append([noel.g, noel.quarter])
    noel.notes.append([noel.d, noel.quarter])
    noel.notes.append([noel.a, noel.quarter])
    noel.notes.append([noel.g, noel.half])
    noel.notes.append([noel.g, noel.eigth])
    noel.notes.append([noel.f, noel.eigth])
    noel.notes.append([noel.e, noel.quarter*1.5])
    noel.notes.append([noel.f, noel.eigth])
    noel.notes.append([noel.g, noel.eigth])
    noel.notes.append([noel.a, noel.eigth])
    noel.notes.append([noel.d, noel.half])
    noel.notes.append([noel.g, noel.eigth])
    noel.notes.append([noel.f, noel.eigth])
    noel.notes.append([noel.e, noel.half])
    noel.notes.append([noel.e, noel.quarter])

    noel.notes.append([noel.d, noel.half*1.5])
    noel.notes.append([noel.g, noel.quarter])
    noel.notes.append([noel.f, noel.quarter])
    noel.notes.append([noel.e, noel.quarter])
    noel.notes.append([noel.d, noel.quarter])
    noel.notes.append([noel.e, noel.quarter])
    noel.notes.append([noel.f, noel.quarter])
    noel.notes.append([noel.g, noel.quarter])
    noel.notes.append([noel.d, noel.quarter])
    noel.notes.append([noel.a, noel.quarter])
    noel.notes.append([noel.g, noel.half])
    #noel.notes.append([noel.rest, noel.eigth])

    noel.size = len(noel.notes)
 
    return noel


